version: 0.0.1

server:
  port: 8080

spring:
  datasource:

    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd
#      driverClassName: com.impossibl.postgres.jdbc.PGDriver
  flyway:
    enabled: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE


#ws:
#  url: localhost
#  port: 8080
#  login: wsusr
#  password: wspwd
#  testdata: true